name: Build Go App for macOS

# 作成されるアプリケーション
# Build_App/FolderWebSarver

# .github/workflows/build.yml


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build for macOS Intel (amd64)
        run: |
          mkdir -p Project/Build_App
          GOOS=darwin GOARCH=amd64 go build -o Project/Build_App/AABBCC-amd64 ./Project/main.go

      - name: Build for macOS Apple Silicon (arm64)
        run: |
          mkdir -p Project/Build_App
          GOOS=darwin GOARCH=arm64 go build -o Project/Build_App/AABBCC-arm64 ./Project/main.go

      - name: Show build results
        run: ls -l Project/Build_App


