name: Build Go Universal Binary for macOS

# 作成されるアプリケーション
# Build_App/FolderWebSarver

# .github/workflows/build.yml

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest   # 重要（lipoはmacOS専用）

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'

      - name: Build amd64
        run: |
          mkdir -p Project/Build_App
          GOOS=darwin GOARCH=amd64 go build -v -o Project/Build_App/AABBCC-amd64 ./Project/main.go
          echo "=== after amd64 build ==="
          ls -lh Project/Build_App

      - name: Build arm64
        run: |
          GOOS=darwin GOARCH=arm64 go build -v -o Project/Build_App/AABBCC-arm64 ./Project/main.go
          echo "=== after arm64 build ==="
          ls -lh Project/Build_App

      - name: Lipo merge
        run: |
          lipo -create -output Project/Build_App/AABBCC \
            Project/Build_App/AABBCC-amd64 Project/Build_App/AABBCC-arm64
          echo "=== after lipo ==="
          ls -lh Project/Build_App
