name: Build Go Application

# 作成されるアプリケーション
# BuildApp/FolderWebSarver

on:
  push:
    branches:
      - main # mainブランチへのプッシュでトリガー

jobs:
  build:
    runs-on: ubuntu-latest # macOSのビルドジョブを別途設定します

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1' # 使用するGoのバージョンを指定してください

jobs:
  build-intel-mac:
    runs-on: macos-latest # Intel Mac環境を指定 (macOS runnerはIntelベースです)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1' # 使用するGoのバージョンを指定してください

      - name: Build for Intel Mac
        run: |
          GOOS=darwin GOARCH=amd64 go build -o Build\ App/AAAAAAAA main.go

      - name: Upload Artifacts (Intel)
        uses: actions/upload-artifact@v4
        with:
          name: intel-mac-app
          path: BuildApp/FolderWebSarver

  build-apple-silicon-mac:
    runs-on: macos-latest # Apple Silicon Mac環境を指定 (macOS runnerはRosetta 2経由でIntelアプリも実行可能ですが、ネイティブビルドが望ましい)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1' # 使用するGoのバージョンを指定してください

      - name: Build for Apple Silicon
        run: |
          GOOS=darwin GOARCH=arm64 go build -o BuildApp/FolderWebSarver main.go

      - name: Upload Artifacts (Apple Silicon)
        uses: actions/upload-artifact@v4
        with:
          name: apple-silicon-mac-app
          path: BuildApp/FolderWebSarver
          
